import turtle                       #One of my quizzes based on science

screen = turtle.Screen()
screen.bgcolor("black")

quiz_bot = turtle.Turtle()
quiz_bot.color("white")
quiz_bot.speed(2)               #Preparing Turtle

quiz_bot.penup()
quiz_bot.goto(-315, 240)
quiz_bot.pendown()
quiz_bot.write("This is the SCIENCE QUIZ, Lets start the questions.. ", font=("Impact", 15, "normal"))
quiz_bot.penup()
quiz_bot.goto(-315, 220)
quiz_bot.pendown()
quiz_bot.write("So the first question is from Physics...", font=("Impact", 15, "normal"))       #1
quiz_bot.penup()
quiz_bot.goto(-315, 180)
quiz_bot.pendown()
quiz_bot.write("What is the closest star to Earth?", font=("Impact", 15, "normal"))
quiz_bot.penup()
quiz_bot.goto(-315, 150)
quiz_bot.pendown()
quiz_bot.write("a) Betelgeuse", font=("Impact", 15, "normal"))
quiz_bot.penup()
quiz_bot.goto(-315, 130)
quiz_bot.pendown()
quiz_bot.write("b) Alpha Centauri", font=("Impact", 15, "normal"))
quiz_bot.penup()
quiz_bot.goto(-315, 110)
quiz_bot.pendown()
quiz_bot.write("c) Proxima Centauri", font=("Impact", 15, "normal"))
quiz_bot.penup()
quiz_bot.goto(-315, 90)
quiz_bot.pendown()
quiz_bot.write("d) Sirius", font=("Impact", 15, "normal"))
quiz_bot.penup()
quiz_bot.goto(-315, 50)
quiz_bot.pendown()
quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
quiz_bot.penup()

a = input("Answer here:- ")
if a == "c" or a == "Proxima Centauri" or a == "c) Proxima Centauri":
    quiz_bot.clear()
    quiz_bot.goto(-315, 0)
    quiz_bot.pendown()
    quiz_bot.write("Great!.. You are absolutely correct..", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, 220)
    quiz_bot.pendown()
    quiz_bot.write("Now for the next Question which is from Chemistry", font=("Impact", 15, "normal"))       #2
    quiz_bot.penup()
    quiz_bot.goto(-315, 200)
    quiz_bot.pendown()
    quiz_bot.write("Which of the following compounds is known as the 'king of chemicals'", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, 180)
    quiz_bot.pendown()
    quiz_bot.write("and is extensively used in the production of fertilizers and explosives", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, 150)
    quiz_bot.pendown()
    quiz_bot.write("a) Sodium Chloride", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, 130)
    quiz_bot.pendown()
    quiz_bot.write("b) Sulfuric Acid", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, 110)
    quiz_bot.pendown()
    quiz_bot.write("c) Nitroglycerin", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, 90)
    quiz_bot.pendown()
    quiz_bot.write("d) Ammonium Nitrate", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, 50)
    quiz_bot.pendown()
    quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
    quiz_bot.penup()

    b = input("Answer here (2):- ")
    if b == "b" or b == "Sulfuric Acid" or b == "b) Sulfuric Acid":
        quiz_bot.clear()
        quiz_bot.goto(-315, 0)
        quiz_bot.pendown()
        quiz_bot.write("Great!.. You are absolutely correct once more..", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.goto(-315, 220)
        quiz_bot.pendown()
        quiz_bot.write("Now for the 3rd Question from Biology...", font=("Impact", 15, "normal"))       #3
        quiz_bot.penup()
        quiz_bot.goto(-315, 200)
        quiz_bot.pendown()
        quiz_bot.write("How many species of organisms are on earth (right now)?", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.goto(-315, 150)
        quiz_bot.pendown()
        quiz_bot.write("a) 2.13 M", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.goto(-315, 130)
        quiz_bot.pendown()
        quiz_bot.write("b) 234 M ", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.goto(-315, 110)
        quiz_bot.pendown()
        quiz_bot.write("c) 1.432 B", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.goto(-315, 90)
        quiz_bot.pendown()
        quiz_bot.write("d) 23 M", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.goto(-315, 50)
        quiz_bot.pendown()
        quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
        quiz_bot.penup()

        c= input("Answer here (3):- ")
        if c == "a" or "2.13 M" or "a) 2.13 M":
            quiz_bot.clear()
            quiz_bot.goto(-315, 0)
            quiz_bot.pendown()
            quiz_bot.write("Great!.. You have completed 3 Questions!!", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.goto(-315, 220)
            quiz_bot.pendown()
            quiz_bot.write("Now for the 4th Question from geography...", font=("Impact", 15, "normal"))       #4
            quiz_bot.penup()
            quiz_bot.goto(-315, 200)
            quiz_bot.pendown()
            quiz_bot.write("What is the capital of Iceland?", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.goto(-315, 150)
            quiz_bot.pendown()
            quiz_bot.write("a) Huyreas", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.goto(-315, 130)
            quiz_bot.pendown()
            quiz_bot.write("b) Kuru", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.goto(-315, 110)
            quiz_bot.pendown()
            quiz_bot.write("c) Gyverks", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.goto(-315, 90)
            quiz_bot.pendown()
            quiz_bot.write("d) Reykjavik", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.goto(-315, 50)
            quiz_bot.pendown()
            quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
            quiz_bot.penup()

            d= input("Answer here (4):- ")
            if d == "d" or "Reykjavik" or "d) Reykjavik":
                quiz_bot.clear()
                quiz_bot.goto(-315, 0)
                quiz_bot.pendown()
                quiz_bot.write("Great!.. You have completed 4 Questions!!", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.goto(-315, 220)
                quiz_bot.pendown()
                quiz_bot.write("Now for the 5th Question from Political Sc...", font=("Impact", 15, "normal"))       #5
                quiz_bot.penup()
                quiz_bot.goto(-315, 200)
                quiz_bot.pendown()
                quiz_bot.write("In international relations, what does the acronym 'NATO' stand for?", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.goto(-315, 150)
                quiz_bot.pendown()
                quiz_bot.write("a) North American Treaty Organization", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.goto(-315, 130)
                quiz_bot.pendown()
                quiz_bot.write("b) North Atlantic Treaty Organization", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.goto(-315, 110)
                quiz_bot.pendown()
                quiz_bot.write("c) North African Treaty Organization", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.goto(-315, 90)
                quiz_bot.pendown()
                quiz_bot.write("d) National Association of Treaty Organizations", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.goto(-315, 50)
                quiz_bot.pendown()
                quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
                quiz_bot.penup()

                e= input("Answer here (5):- ")
                if e == "b" or "North Atlantic Treaty Organization" or "b) North Atlantic Treaty Organization":
                    quiz_bot.clear()
                    quiz_bot.goto(-315, 0)
                    quiz_bot.pendown()
                    quiz_bot.write("Great!.. You are halfway there!!", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.goto(-315, 220)
                    quiz_bot.pendown()
                    quiz_bot.write("Now for the 6th Question from History...", font=("Impact", 15, "normal"))       #6
                    quiz_bot.penup()
                    quiz_bot.goto(-315, 200)
                    quiz_bot.pendown()
                    quiz_bot.write("Which ancient civilization built the famous city of Machu Picchu?", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.goto(-315, 150)
                    quiz_bot.pendown()
                    quiz_bot.write("a) Aztec Empire", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.goto(-315, 130)
                    quiz_bot.pendown()
                    quiz_bot.write("b) Inca Empire", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.goto(-315, 110)
                    quiz_bot.pendown()
                    quiz_bot.write("c) Maya Civilization", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.goto(-315, 90)
                    quiz_bot.pendown()
                    quiz_bot.write("d) Ancient Egypt", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.goto(-315, 50)
                    quiz_bot.pendown()
                    quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
                    quiz_bot.penup()

                    e= input("Answer here (6):- ")
                    if e == "b" or "Inca Empire" or "b) Inca Empire":
                        quiz_bot.clear()
                        quiz_bot.goto(-315, 0)
                        quiz_bot.pendown()
                        quiz_bot.write("Great!.. Good going!!", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.goto(-315, 220)
                        quiz_bot.pendown()
                        quiz_bot.write("Now for the 7th Question from Economics...", font=("Impact", 15, "normal"))       #7
                        quiz_bot.penup()
                        quiz_bot.goto(-315, 200)
                        quiz_bot.pendown()
                        quiz_bot.write("What describes the situation where the government spends more money than it receives in Taxes?", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.goto(-315, 150)
                        quiz_bot.pendown()
                        quiz_bot.write("a) Budget surplus", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.goto(-315, 130)
                        quiz_bot.pendown()
                        quiz_bot.write("b) Deflation", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.goto(-315, 110)
                        quiz_bot.pendown()
                        quiz_bot.write("c) Budget deficit", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.goto(-315, 90)
                        quiz_bot.pendown()
                        quiz_bot.write("d) Inflation", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.goto(-315, 50)
                        quiz_bot.pendown()
                        quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
                        quiz_bot.penup()

                        f= input("Answer here (7):- ")
                        if f == "c" or "Budget deficit" or "c) Budget deficit":                 
                            quiz_bot.clear()
                            quiz_bot.goto(-315, 0)
                            quiz_bot.pendown()
                            quiz_bot.write("Great!.. Are you cheating?", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.goto(-315, 220)
                            quiz_bot.pendown()
                            quiz_bot.write("Now for the 8th Question from Psychology...", font=("Impact", 15, "normal"))       #8
                            quiz_bot.penup()
                            quiz_bot.goto(-315, 200)
                            quiz_bot.pendown()
                            quiz_bot.write("Which of the following is a neurotransmitter associated with pleasure and reward?", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.goto(-315, 150)
                            quiz_bot.pendown()
                            quiz_bot.write("a) Dopamine", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.goto(-315, 130)
                            quiz_bot.pendown()
                            quiz_bot.write("b) Serotonin", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.goto(-315, 110)
                            quiz_bot.pendown()
                            quiz_bot.write("c) Acetylcholine", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.goto(-315, 90)
                            quiz_bot.pendown()
                            quiz_bot.write("d) GABA", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.goto(-315, 50)
                            quiz_bot.pendown()
                            quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
                            quiz_bot.penup()

                            f= input("Answer here (8):- ")
                            if f == "a" or "Dopamine" or "a) Dopamine":
                                quiz_bot.clear()
                                quiz_bot.goto(-315, 0)
                                quiz_bot.pendown()
                                quiz_bot.write("Great!.. I see Perfection!!", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.goto(-315, 220)
                                quiz_bot.pendown()
                                quiz_bot.write("Now for the 9th Question from Computer Sciences...", font=("Impact", 15, "normal"))       #9
                                quiz_bot.penup()
                                quiz_bot.goto(-315, 200)
                                quiz_bot.pendown()
                                quiz_bot.write("What is the process of converting a high-level programming language into machine code?", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.goto(-315, 150)
                                quiz_bot.pendown()
                                quiz_bot.write("a) Interpretation", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.goto(-315, 130)
                                quiz_bot.pendown()
                                quiz_bot.write("b) Execution", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.goto(-315, 110)
                                quiz_bot.pendown()
                                quiz_bot.write("c) Debugging", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.goto(-315, 90)
                                quiz_bot.pendown()
                                quiz_bot.write("d) Compilation", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.goto(-315, 50)
                                quiz_bot.pendown()
                                quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
                                quiz_bot.penup()

                                g= input("Answer here (9):- ")
                                if g == "d" or "Compilation" or "d) Compilation":
                                    quiz_bot.clear()
                                    quiz_bot.goto(-315, 0)
                                    quiz_bot.pendown()
                                    quiz_bot.write("Great!.. Just There!!", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, 220)
                                    quiz_bot.pendown()
                                    quiz_bot.write("Now for the 10th and Final Question from Mathematical Sciences...", font=("Impact", 15, "normal"))       #10
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, 200)
                                    quiz_bot.pendown()
                                    quiz_bot.write("What is the value of '5^3 - 2^4 + 6' ?", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, 150)
                                    quiz_bot.pendown()
                                    quiz_bot.write("a) 89", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, 130)
                                    quiz_bot.pendown()
                                    quiz_bot.write("b) 119", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, 110)
                                    quiz_bot.pendown()
                                    quiz_bot.write("c) 99", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, 90)
                                    quiz_bot.pendown()
                                    quiz_bot.write("d) 109", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, 50)
                                    quiz_bot.pendown()
                                    quiz_bot.write("Please Answer in the Panel...", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()

                                    h= input("Answer here (10):- ")
                                    if g == "b" or "119" or "b) 119":
                                        quiz_bot.clear()
                                        quiz_bot.goto(-315, 0)
                                        quiz_bot.pendown()
                                        quiz_bot.write("Wonderful! You have completed the 10 Ques of Science!", font=("Impact", 15, "normal"))
                                        quiz_bot.penup()
                                        quiz_bot.goto(-315, -50)
                                        quiz_bot.pendown()
                                        quiz_bot.write("Now to Verify your win I am providing you a COUPON OF COMPLETION ", font=("Impact", 15, "normal"))
                                        quiz_bot.penup()
                                        quiz_bot.goto(-315, -65)
                                        quiz_bot.pendown()
                                        quiz_bot.write("So the code is...", font=("Impact", 15, "normal"))
                                        quiz_bot.penup()
                                        quiz_bot.goto(-315, -100)
                                        quiz_bot.pendown()
                                        quiz_bot.write("SCI2468", font=("Impact", 25, "bold"))       #Code for Ans. key
                                        quiz_bot.penup()
                                        quiz_bot.hideturtle()
                                        turtle.done()
                                        exit()
                                    else:
                                        quiz_bot.clear()                                              #If any Ans is incorrect...
                                        quiz_bot.goto(-315, 0)
                                        quiz_bot.pendown()
                                        quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
                                        quiz_bot.penup()
                                        quiz_bot.goto(-315, -20)
                                        quiz_bot.pendown()
                                        quiz_bot.write("Final Score==> '9/10' ", font=("Impact", 15, "normal"))
                                        quiz_bot.penup()
                                        quiz_bot.hideturtle()
                                        turtle.done()
                                        exit()
                                else:
                                    quiz_bot.clear()
                                    quiz_bot.goto(-315, 0)
                                    quiz_bot.pendown()
                                    quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.goto(-315, -20)
                                    quiz_bot.pendown()
                                    quiz_bot.write("Final Score==> '8/10' ", font=("Impact", 15, "normal"))
                                    quiz_bot.penup()
                                    quiz_bot.hideturtle()
                                    turtle.done()
                                    exit()
                            else:
                                quiz_bot.clear()
                                quiz_bot.goto(-315, 0)
                                quiz_bot.pendown()
                                quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.goto(-315, -20)
                                quiz_bot.pendown()
                                quiz_bot.write("Final Score==> '7/10' ", font=("Impact", 15, "normal"))
                                quiz_bot.penup()
                                quiz_bot.hideturtle()
                                turtle.done()
                                exit()
                        else:
                            quiz_bot.clear()
                            quiz_bot.goto(-315, 0)
                            quiz_bot.pendown()
                            quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.goto(-315, -20)
                            quiz_bot.pendown()
                            quiz_bot.write("Final Score==> '6/10' ", font=("Impact", 15, "normal"))
                            quiz_bot.penup()
                            quiz_bot.hideturtle()
                            turtle.done()
                            exit()
                    else:
                        quiz_bot.clear()
                        quiz_bot.goto(-315, 0)
                        quiz_bot.pendown()
                        quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.goto(-315, -20)
                        quiz_bot.pendown()
                        quiz_bot.write("Final Score==> '5/10' ", font=("Impact", 15, "normal"))
                        quiz_bot.penup()
                        quiz_bot.hideturtle()
                        turtle.done()
                        exit()
                else:
                    quiz_bot.clear()
                    quiz_bot.goto(-315, 0)
                    quiz_bot.pendown()
                    quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.goto(-315, -20)
                    quiz_bot.pendown()
                    quiz_bot.write("Final Score==> '4/10' ", font=("Impact", 15, "normal"))
                    quiz_bot.penup()
                    quiz_bot.hideturtle()
                    turtle.done()
                    exit()
            else:
                quiz_bot.clear()
                quiz_bot.goto(-315, 0)
                quiz_bot.pendown()
                quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.goto(-315, -20)
                quiz_bot.pendown()
                quiz_bot.write("Final Score==> '3/10' ", font=("Impact", 15, "normal"))
                quiz_bot.penup()
                quiz_bot.hideturtle()
                turtle.done()
                exit()
        else:
            quiz_bot.clear()
            quiz_bot.goto(-315, 0)
            quiz_bot.pendown()
            quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.goto(-315, -20)
            quiz_bot.pendown()
            quiz_bot.write("Final Score==> '2/10' ", font=("Impact", 15, "normal"))
            quiz_bot.penup()
            quiz_bot.hideturtle()
            turtle.done()
            exit()
        
    else:
        quiz_bot.clear()
        quiz_bot.goto(-315, 0)
        quiz_bot.pendown()
        quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.goto(-315, -20)
        quiz_bot.pendown()
        quiz_bot.write("Final Score==> '1/10' ", font=("Impact", 15, "normal"))
        quiz_bot.penup()
        quiz_bot.hideturtle()
        turtle.done()
        exit()
else:
    quiz_bot.clear()
    quiz_bot.goto(-315, 0)
    quiz_bot.pendown()
    quiz_bot.write("You are wrong!!", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.goto(-315, -20)
    quiz_bot.pendown()
    quiz_bot.write("Final Score==> '0/10' ", font=("Impact", 15, "normal"))
    quiz_bot.penup()
    quiz_bot.hideturtle()
    turtle.done()
    exit()